In [ ]:
We use regex to:

👉 Search
👉 Validate Email validation
👉 Extract  Extract Data from Text
👉 Replace
👉 Clean text

In [1]:
from re import re

In [ ]:
Python does NOT support regex directly by default.
So we must import the module to use regex functions.

In [14]:
text = "Python I am learning Python Python "

result = re.findall("(Python)+",text)
print(result)
if result:
    print("Found!")
else:
    print("Not Found")

['Python', 'Python', 'Python']
Found!

In [ ]:
Function	Purpose
re.search()	Finds first match anywhere in string
re.match()	Checks match at beginning of string
re.findall()	Returns all matches as a list
re.sub()	Replace matched text
re.split()	Split string using pattern

In [ ]:
Symbol	Meaning	Example
.	Any character except newline	a.c → abc, axc
^	Start of string	^Hello
$	End of string	world$
*	0 or more times	ab*  a,ab,abb
+	1 or more times	ab+  ab,abb
?	0 or 1 time	ab?   previous letter
\d	Digit (0–9)	\d\d  [0-9]  [a z 0-9
\w	Word character	letters, digits
\s	Space	
[]	Set of characters	[abc]
{4}fixed

In [ ]:
# extract only number

In [3]:
text = "My marks are 85 and 90"

numbers = re.findall("\d+", text)

print(numbers)

['85', '90']

In [ ]:
\d+ means:

\d → digit

+ → one or more

In [ ]:
# valid email

In [5]:
email = "renu89@gmail.com"

pattern = r"^\w+@\w+\.\w+$"

if re.match(pattern, email):
    print("Valid Email")
else:
    print("Invalid Email")   # beginning only

Valid Email

In [7]:
text = "My email is renu@gmail.com"

pattern = r"\w+@\w+\.\w+"

result = re.search(pattern, text)
print(result)   # anywhere

<re.Match object; span=(12, 26), match='renu@gmail.com'>

In [8]:
print(result.group())

renu@gmail.com

In [ ]:
# valid phone number

In [16]:
text = "My number is 89999999999876543210"

result = re.findall(r"\b\d{10}\b", text)
print(result)

[]

In [ ]:
Has exactly 10 digits
re.findall():

Returns ALL matches
Is not attached to other numbers or characters

In [ ]:
# Validate Indian PAN Card

In [ ]:
Format: 5 letters + 4 digits + 1 letter
Example: ABCDE1234F

pan = "ABCDE1234F"

pattern = r"^[A-Z]{5}[0-9]{4}[A-Z]$"

if re.match(pattern, pan):
    print("Valid PAN")
else:
    print("Invalid PAN")

In [28]:
import pandas as pd

data = {
    "name": ["     Renu", "Amit", "Priya", "John123"],
    "email": ["renu@gmail.com", "amit@yahoo.in", "invalid_email", "john123@gmail.com"],
    "phone": ["9876543210", "12345", "9999999999", "abc9876543"]
}

df = pd.DataFrame(data)
df

      name              email       phone
0     Renu     renu@gmail.com  9876543210
1     Amit      amit@yahoo.in       12345
2    Priya      invalid_email  9999999999
3  John123  john123@gmail.com  abc9876543

In [29]:
df.columns

Index(['name', 'email', 'phone'], dtype='object')

RangeIndex(start=0, stop=1, step=1)

In [13]:
#Extract Only Valid Phone Numbers (10 digits)
df["valid_phone"] = df["phone"].str.match(r"^\d{10}$")

df

#👉 .str.match() checks from beginning (like re.match())

      name              email       phone  valid_phone
0     Renu     renu@gmail.com  9876543210         True
1     Amit      amit@yahoo.in       12345        False
2    Priya      invalid_email  9999999999         True
3  John123  john123@gmail.com  abc9876543        False

In [15]:
df["numbers_in_name"] = df["name"].str.extract(r"(\d+)")

df

      name              email       phone  valid_phone numbers_in_name
0     Renu     renu@gmail.com  9876543210         True             NaN
1     Amit      amit@yahoo.in       12345        False             NaN
2    Priya      invalid_email  9999999999         True             NaN
3  John123  john123@gmail.com  abc9876543        False             123

In [18]:
df

      name              email       phone
0     Renu     renu@gmail.com  9876543210
1     Amit      amit@yahoo.in       12345
2    Priya      invalid_email  9999999999
3  John123  john123@gmail.com  abc9876543

In [30]:
df[['a','b']]=df['email'].str.split("@",expand=True)

In [31]:
df

      name              email       phone              a          b
0     Renu     renu@gmail.com  9876543210           renu  gmail.com
1     Amit      amit@yahoo.in       12345           amit   yahoo.in
2    Priya      invalid_email  9999999999  invalid_email       None
3  John123  john123@gmail.com  abc9876543        john123  gmail.com